import { jsPDF } from "jspdf";

interface ReportData {
  trackingId: string;
  severity: string;
  category: string;
  description: string;
  occurredAt: string;
  location: string;
  fileCount: number;
  submittedAt: string;
}

const CATEGORY_LABELS: Record<string, string> = {
  FRAUD: "Financial Misconduct",
  HARASSMENT: "Harassment & Bullying",
  DISCRIMINATION: "Discrimination",
  DATA_MISUSE: "Data & Privacy Breach",
  POLICY_VIOLATION: "Policy Violation",
  SAFETY_CONCERN: "Health & Safety",
  CORRUPTION: "Corruption & Bribery",
  ENVIRONMENTAL: "Environmental Concern",
  RETALIATION: "Retaliation",
  OTHER: "Other Concern",
};

export function generateReportPdf(data: ReportData) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = 20;

  /* ── Header bar ── */
  doc.setFillColor(20, 25, 35); // Dark bg
  doc.rect(0, 0, pageWidth, 40, "F");

  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(255, 255, 255);
  doc.text("SpeakSafe", margin, 18);

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(160, 170, 180);
  doc.text("Confidential Disclosure Report", margin, 26);

  doc.setFontSize(9);
  doc.text(`Generated: ${formatDate(data.submittedAt)}`, margin, 33);

  y = 52;

  /* ── Tracking ID ── */
  doc.setFillColor(30, 38, 50);
  doc.roundedRect(margin, y, contentWidth, 20, 3, 3, "F");

  doc.setFontSize(8);
  doc.setTextColor(120, 200, 140);
  doc.setFont("helvetica", "bold");
  doc.text("TRACKING ID", margin + 8, y + 8);

  doc.setFontSize(16);
  doc.setTextColor(120, 200, 140);
  doc.setFont("courier", "bold");
  doc.text(data.trackingId, margin + 8, y + 16);

  // Severity badge on the right
  const severityColors: Record<string, [number, number, number]> = {
    CRITICAL: [220, 50, 50],
    HIGH: [230, 120, 40],
    MEDIUM: [200, 180, 50],
    LOW: [80, 180, 120],
  };
  const [r, g, b] = severityColors[data.severity] ?? [150, 150, 150];
  const badgeText = data.severity;
  const badgeWidth = doc.getTextWidth(badgeText) * 1.8 + 10;

  doc.setFillColor(r, g, b);
  doc.roundedRect(
    pageWidth - margin - badgeWidth,
    y + 4,
    badgeWidth,
    12,
    2,
    2,
    "F",
  );
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(255, 255, 255);
  doc.text(
    badgeText,
    pageWidth - margin - badgeWidth / 2,
    y + 11.5,
    { align: "center" },
  );

  y += 30;

  /* ── Section: Details ── */
  y = drawSectionHeader(doc, "Report Details", margin, y);

  y = drawField(doc, "Category", CATEGORY_LABELS[data.category] ?? data.category, margin, y, contentWidth);

  if (data.occurredAt) {
    y = drawField(doc, "Date of Incident", formatDateShort(data.occurredAt), margin, y, contentWidth);
  }
  if (data.location) {
    y = drawField(doc, "Location", data.location, margin, y, contentWidth);
  }
  y = drawField(doc, "Evidence Files", `${data.fileCount} file(s) attached`, margin, y, contentWidth);

  y += 4;

  /* ── Section: Description ── */
  y = drawSectionHeader(doc, "Description of Concern", margin, y);

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(50, 55, 60);
  const lines = doc.splitTextToSize(data.description, contentWidth - 4);
  for (const line of lines) {
    if (y > 270) {
      doc.addPage();
      y = 20;
    }
    doc.text(line, margin + 2, y);
    y += 5;
  }

  y += 8;

  /* ── Footer ── */
  if (y > 250) {
    doc.addPage();
    y = 20;
  }

  doc.setDrawColor(200, 205, 210);
  doc.line(margin, y, pageWidth - margin, y);
  y += 6;

  doc.setFontSize(7.5);
  doc.setTextColor(140, 145, 155);
  doc.setFont("helvetica", "italic");
  doc.text(
    "This document is confidential. It was generated by the SpeakSafe whistleblowing platform.",
    margin,
    y,
  );
  y += 4;
  doc.text(
    "Do not share this document with unauthorized individuals. Store securely.",
    margin,
    y,
  );

  /* ── Save ── */
  doc.save(`SpeakSafe-Report-${data.trackingId}.pdf`);
}

function drawSectionHeader(
  doc: jsPDF,
  title: string,
  margin: number,
  y: number,
): number {
  doc.setFillColor(120, 200, 140);
  doc.rect(margin, y, 2, 10, "F");

  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(30, 35, 45);
  doc.text(title, margin + 6, y + 7);

  return y + 16;
}

function drawField(
  doc: jsPDF,
  label: string,
  value: string,
  margin: number,
  y: number,
  _contentWidth: number,
): number {
  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(120, 125, 135);
  doc.text(label.toUpperCase(), margin + 4, y);

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(50, 55, 60);
  doc.text(value, margin + 4, y + 5.5);

  return y + 12;
}

function formatDate(iso: string): string {
  try {
    return new Date(iso).toLocaleString("en-US", {
      year: "numeric",
      month: "long",
      day: "numeric",
      hour: "2-digit",
      minute: "2-digit",
    });
  } catch {
    return iso;
  }
}

function formatDateShort(dateStr: string): string {
  try {
    const d = new Date(dateStr + "T00:00:00");
    return d.toLocaleDateString("en-US", {
      year: "numeric",
      month: "long",
      day: "numeric",
    });
  } catch {
    return dateStr;
  }
}
